#baseURL = 'https://120.48.161.177'
baseURL = 'https://blog.yupengfei.xyz'
#baseURL = 'https://mryupengfei.github.io'
languageCode = 'en-us'
title = 'My Public Site'
theme = "hugo-cards"
[pagination]
  pagerSize = 6

[params]
  builtBy = "Yu Pengfei (于鹏飞)"
  defaultImage = "gopher.jpg"

  facebook = ""
  quora = ""
  twitter = ""
  github = "https://github.com/MrYuPengfei"
  email = "yupengfei.edu@gmail.com"

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = ""
  fbPageTitle = ""

  disqus = ""

  custom_css = ["css/custom.css"]

  #[params.post.meta]
  #  isHidden = true

  #[params.post.sidebar]
  #  type = "profile"
  #  title = "Profile"

  [params.analytics]
    type="UA"
    trackingID = ""

  [params.copyright]
     name = "Yu Pengfei (于鹏飞)"
     link = "https://mryupengfei.github.io"
  [params.Author]
    name = "MrYuPengfei"       # 你的作者名
    email = "mr_yupengfei@foxmail.com"  # 你的邮箱
    url = "https://github.com/MrYuPengfei"  # 你的个人链接
